### PR TITLE
Make CenterNet work without Conda

### PR DESCRIPTION
**Pull request by SuriyaNitt**
Hi,

 Thanks for opening sourcing this amazing work.

While trying to follow the installation, I came across a few issues and tried to address them in four different commits.

1. I was facing undefined symbol (__cudaPopCallConfiguration) issue with _dcn_v2.so. Fixed this in commit 1
2. osp.dirname was returning empty string for me. This is fixed in commit 2
3. python by default points to python2 in some machines. So, without conda, explicitly mentioning python version could be useful
4. Added __init__.py to folders to be treated as python packages.

Let me know if separate PRs are need. Happy to contribute!

### CODE REVIEW

**Comment by xingyizhou** [comment]
Hi, 
  Thanks very much for the contribution. They are very helpful. 
  1. Hard code `/usr/local/cuda/lib64` is not ideal, some server machine does not locate cuda this way and the user (including myself) is not able to change the cuda directory without root.
  2. I use `CenterNet_ROOT ` just for easy documenting the path in the readme. Most users (including myself) do not really create the environment variable. 
  3. This can be resolved automatically if the user set a conda environment.
  4. I will accept this if you pull it separately.

**Comment by nopattern** [comment]
cudaPopCallConfiguration  problem too. linux without conda.

**Comment by poddar414** [comment]
HI Surya,

I am also facing #1 problem. I have following environment variable set

PATH=$PATH:"/usr/local/cuda/bin"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/local/cuda/lib64"
export CUDA_HOME=/usr/local/cuda

any clue? i have CUDA 10.0 with pytorch 0.4.1

**Comment by poddar414** [comment]
problem got solve by installing pytorch 1.0 and using original repository of DCNv2. Atleast I could use the demo script.
Thanks for the making this work public.

**Pull request closed without merging**
