### PR TITLE
Fix the gaussian radius calculation error

### PR DESCRIPTION
**Pull request by niaoyu**
Accorrding to the source of gaussian radius calculation-, the bug should be fixed.
[Cornet gaussian radius bug](https://github.com/princeton-vl/CornerNet/commit/3e71377b45098f9cea26d5a39de0138174c90d49#diff-dfdd6e442651f218d8d80794a8ddf7fd)

### CODE REVIEW

**Comment by xingyizhou** [comment]
Thanks for creating the pull request. But we haven't verified if it will help/ hurt the performance. We will be happy to merge this if you have verified this for all the tasks (using DLA models) and provide the trained models and logs.

**Comment by ujsyehao** [comment]
＠niaoyu Why use '-' ?

**Comment by ujsyehao** [comment]
@xingyizhou I have verified it on my own dataset(use mobilenetv2 backbone)
centernet gaussian radius: 61.3mAP(IOU@0.5)
cornet gaussian readius(fixed): 57.1mAP(IOU@0.5)

**Comment by feixiangdekaka** [comment]
> @xingyizhou I have verified it on my own dataset(use mobilenetv2 backbone)
> centernet gaussian radius: **61.3mAP(IOU@0.5)**
> cornet gaussian radius(fixed): **57.1mAP(IOU@0.5)**

the modified version becomes worse?

**Pull request closed without merging**
